Reverting dryrun changes for release
This __should__ fix the release logic...

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,8 +1,8 @@
 name: Release Helm Chart
 on:
   push:
-    branches:
-      fix-actions-and-file-tree
+    tags:
+      - 'v*'
 jobs:
   build:
     runs-on: ubuntu-22.04
@@ -21,20 +21,19 @@ jobs:
       - name: Extract chart version from tag
         id: version
         run: |
-          # VERSION=${GITHUB_REF#refs/tags/v}
-          # if [[ $(helm version --short) != $(echo $VERSION | sed s/v//g) ]]; then 
-          #   echo "Error: release name mismatch!"
-          #   exit 1
-          # fi
+          VERSION=${GITHUB_REF#refs/tags/v}
+          if [[ $(helm show chart . | grep -E "^version:" | awk '{print $2}') != $(echo $VERSION | sed s/v//g) ]]; then 
+            echo "Error: release name mismatch!"
+            exit 1
+          fi
 
-          # docker manifest inspect ghcr.io/${{ github.repository }}:$VERSION > /dev/null 2>&1
-          # if [ $? -eq 0 ]; then
-          #   echo "Error: version already exists in registry"
-          #   exit 1
-          # fi
+          docker manifest inspect ghcr.io/${{ github.repository }}:$VERSION > /dev/null 2>&1
+          if [ $? -eq 0 ]; then
+            echo "Error: version already exists in registry"
+            exit 1
+          fi
           
-          echo "VERSION=$(helm version --short)" >> $GITHUB_OUTPUT
-          echo "DRYRUN"
+          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
         shell: bash
       
       - name: Package Helm chart
@@ -49,6 +48,7 @@ jobs:
           path: ./nifi-${{ steps.version.outputs.VERSION }}.tgz
   
   deploy:
+    if: ${{ github.ref_type == 'tag' }}
     runs-on: ubuntu-latest
     needs: [build]
     steps:
@@ -70,7 +70,6 @@ jobs:
           for pkg in .chart/*.tgz; do
             if [ -f "$pkg" ]; then
               echo "Pushing ${pkg} to OCI registry"
-              # helm push "${pkg}" "oci://ghcr.io/${{ github.repository_owner }}/charts"
-              echo "DRYRUN"
+              helm push "${pkg}" "oci://ghcr.io/${{ github.repository_owner }}/charts"
             fi
           done
