Updating file system and switching to use ghcr.io
This allows proper version control for end users using the chart. Previous way to host on pages, forces users to use the most updated chart. Any bugs introduced in releases. can cause downstream issues for end users.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -6,35 +6,81 @@ on:
       - 'v*'
 
 jobs:
-  release:
+  build:
     runs-on: ubuntu-22.04
 
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
 
+      - name: Log in to GHCR
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
       - name: Set up Helm
         uses: azure/setup-helm@v3
+          
+      - name: Helm lint
+        run: helm lint
 
       - name: Extract chart version from tag
         id: version
         run: |
-          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
+          VERSION=${GITHUB_REF#refs/tags/v}
+          if [[ $(helm version --short) != $(echo $VERSION | sed s/v//g) ]]; then 
+            echo "Error: release name mismatch!"
+            exit 1
+          fi
+
+          docker manifest inspect ghcr.io/${{ github.repository }}:$VERSION > /dev/null 2>&1
+          if [ $? -eq 0 ]; then
+            echo "Error: version already exists in registry"
+            exit 1
+          fi
+          
+          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
+        shell: bash
       
       - name: Package Helm chart
         run: |
-          helm dependency update charts/nifi
-          helm package charts/nifi --version ${{ steps.version.outputs.VERSION }}
-          mkdir -p repo
-          mv nifi-${{ steps.version.outputs.VERSION }}.tgz repo/
+          helm dependency update
+          helm package . --version ${{ steps.version.outputs.VERSION }} --destination .
 
-      - name: Generate Helm repo index
-        run: |
-          helm repo index repo --url https://pnnl.github.io/helm-nifi
-
-      - name: Publish to GitHub Pages
-        uses: peaceiris/actions-gh-pages@v3
+      - name: Upload artifact
+        uses: actions/upload-artifact@v4
         with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: ./repo
-          publish_branch: gh-pages
+          name: nifi
+          path: ./nifi-${{ steps.version.outputs.VERSION }}.tgz
+
+  deploy:
+    if: ${{ github.ref_type == 'tag' }}
+    runs-on: ubuntu-latest
+    needs:  [build]
+    steps:
+      - name: Download Artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: nifi
+          path: .chart
+
+      - name: Login to GitHub Container Registry
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+                    
+      - name: Push charts to GHCR
+        run: |
+          shopt -s nullglob
+          files=$(find .chart/ -type f -name "*.tgz")
+          for pkg in $files; do
+            echo "Pushing ${pkg} to ghcr.io/${{ github.repository_owner }}/charts/helm-nifi"
+            if [ -z "${pkg:-}" ]; then
+              break
+            fi
+            helm push "${pkg}" "oci://ghcr.io/${{ github.repository_owner }}/charts/helm-nifi"
+          done
